In [1]:
#---IMPORTAÇÃO DE BIBLIOTECAS USADAS NO PROJETO---#
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
#---OBTENDO OS DADOS UTILIZADOS, NO FORMATO .CSV E TRANSFORMANDO EM OBJETOS DATAFRAMES COM A BIBLIOTECA PANDAS---#
filmes = pd.read_csv('C:/Users/João Pedro Mendes/Documents/JupyterMeuLab/Lab XI - CPBR/Data/movies.csv')
avaliacoes = pd.read_csv('C:/Users/João Pedro Mendes/Documents/JupyterMeuLab/Lab XI - CPBR/Data/ratings.csv')
#---DUAS VARIÁVEIS, UMA COM OS FILMES E SUAS INFORMAÇÕES E OUTRA COM AS AVALIAÇÕES E SUAS INFORMAÇÕES---#

In [3]:
#---JUNTANDO OS DATAFRAMES ANTERIORES EM UM ÚNICO DATAFRAME E VISUALIZANDO PARA ENTENDER SUA ESTRUTURA---#
dfinfo = pd.merge(filmes, avaliacoes)

#---VERIFICANDO O DATAFRAME---#
dfinfo

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483
...,...,...,...,...,...,...
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,1537109082
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,1537109545
100833,193585,Flint (2017),Drama,184,3.5,1537109805
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,1537110021
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,1537157606

In [4]:
#---REMOÇÃO DE COLUNAS QUE NÃO SERÃO UTILIZADAS DURANTE O PROJETO---#
dfinfo.drop(columns={'timestamp', 'genres'}, inplace=True)

#---VERIFICANDO AS 3 PRIMEIRAS LINHAS DO DATAFRAME---#
dfinfo.head(3)

   movieId             title  userId  rating
0        1  Toy Story (1995)       1     4.0
1        1  Toy Story (1995)       5     4.0
2        1  Toy Story (1995)       7     4.5

In [5]:
#---CRIANDO UM NOVO DATAFRAME PARA GERAR NOSSOS DADOS EM FORMATO DE TABELA DINÂMICA, FACILITANDO A OBSERVAÇÃO DO DF---#
avaliacao_usuario = dfinfo.pivot_table(index=['userId'], columns=['title'], values='rating')

#---VERIFICANDO O DATAFRAME---#
avaliacao_usuario

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.5,3.5,NaN,NaN,NaN
609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,...,NaN,4.0,3.5,3.0,NaN,NaN,2.0,1.5,NaN,NaN

In [66]:
#---ELIMINAMOS OS FILME COM MENOS DE 10 AVALIAÇÕES E PREENCHEMOS OS DADOS AUSENTES POR 0---#
avaliacao_usuario = avaliacao_usuario.dropna(thresh=3, axis=1).fillna(0)

#---VERIFICANDO O DATAFRAME---#
avaliacao_usuario
#---OBSERVAMOS MUITOS VALORES 0.0, QUE ANTERIORMENTE ERAM NaN TENDO EM VISTA QUE NEM TODOS OS USUÁRIOS VIRAM AQUELE DETERMINADO FILME---#

title,"'burbs, The (1989)",(500) Days of Summer (2009),10 Cloverfield Lane (2016),10 Things I Hate About You (1999),"10,000 BC (2008)",101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),12 Angry Men (1957),12 Years a Slave (2013),127 Hours (2010),...,Zack and Miri Make a Porno (2008),Zero Dark Thirty (2012),Zero Effect (1998),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,4.5,3.5,0.0
609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,0.0,3.5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,3.5,0.0,0.0,5.0,3.5,4.0,4.0,0.0,2.0,0.0

In [67]:
#---CRIANDO UMA FUNÇÃO QUE PADRONIZA AS AVALIAÇÕES EM VALORES ENTRE -1 E 1---#
def padronizar(linha):
    
    nova_linha = (linha - linha.mean()/(linha.max()-linha.min()))
    #---(X-MÉDIA(X))/(MÁXIMO(X)-MÍNIMO(X))---#             
    return nova_linha
    #---RETORNAMOS NOSSA NOVA LINHA COMO O RESULTADO DA FUNÇÃO---#

novaavaliacao = avaliacao_usuario.apply(padronizar)
#---FORMAMOS UM NOVO DATAFRAME A PARTIR DA APLICAÇÃO DA NOSSA FUNÇÃO PADRONIZAR NO NOSSO DATAFRAME COM AS AVALIAÇÕES DE USUÁRIOS---#

similaridade_filmes = cosine_similarity(novaavaliacao.T)
#---UTILIZANDO O RECURSO COSINE_SIMILARITY, DA BIBLIOTECA SKLEARN, CRIAMOS UM ARRAY QUE OBTEM OS VALORES DA VARIAVEL---#
#---NOVAAVALIACAO E REALIZA A FUNÇÃO BUILT-IN COSINE_SIMILARITY(SIMILARIDADE PELO COSSENO)---#
print(similaridade_filmes)
#---VERIFICANDO NOSSO ARRAY---#

[[ 1.          0.08692759 -0.00842826 ...  0.20316324  0.07886293
   0.365934  ]
 [ 0.08692759  1.          0.16285695 ...  0.08248916  0.26259983
   0.15425513]
 [-0.00842826  0.16285695  1.         ...  0.19246902  0.11191642
   0.02172672]
 ...
 [ 0.20316324  0.08248916  0.19246902 ...  1.          0.18080721
   0.15919175]
 [ 0.07886293  0.26259983  0.11191642 ...  0.18080721  1.
   0.08681061]
 [ 0.365934    0.15425513  0.02172672 ...  0.15919175  0.08681061
   1.        ]]

In [68]:
#---NOVO DATAFRAME COM A VARIAVEL SIMARILIDADE_FILMES, UTILIZANDO COMO ÍNDICE E COMO COLUNAS, AS COLUNAS---#
#---DO NOSSO DF AVALIACAO_USUARIO---#
dfsimilaridade = pd.DataFrame(similaridade_filmes, index=avaliacao_usuario.columns, columns=avaliacao_usuario.columns)

#---VERIFICANDO O DATAFRAME---#
dfsimilaridade

title,"'burbs, The (1989)",(500) Days of Summer (2009),10 Cloverfield Lane (2016),10 Things I Hate About You (1999),"10,000 BC (2008)",101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),12 Angry Men (1957),12 Years a Slave (2013),127 Hours (2010),...,Zack and Miri Make a Porno (2008),Zero Dark Thirty (2012),Zero Effect (1998),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
title,,,,,,,,,,,,,,,,,,,,,
"'burbs, The (1989)",1.000000,0.086928,-0.008428,0.167556,0.026795,0.112297,0.243882,0.063260,0.024770,0.025111,...,0.035368,0.047057,0.148163,0.173642,0.127035,0.077312,0.025886,0.203163,0.078863,0.365934
(500) Days of Summer (2009),0.086928,1.000000,0.162857,0.308246,0.212890,0.186463,0.179393,0.201092,0.157048,0.221669,...,0.392381,0.198161,0.091769,0.438066,0.386303,0.287615,0.244952,0.082489,0.262600,0.154255
10 Cloverfield Lane (2016),-0.008428,0.162857,1.000000,0.022072,0.125045,0.031759,0.009058,0.059386,-0.009034,0.284616,...,0.255705,0.111984,-0.008327,0.288589,0.261274,0.216106,0.333470,0.192469,0.111916,0.021727
10 Things I Hate About You (1999),0.167556,0.308246,0.022072,1.000000,0.263968,0.262351,0.250294,0.067107,0.117644,0.073070,...,0.267630,0.129110,0.156593,0.133150,0.204191,0.320612,0.089847,0.151127,0.158846,0.143195
"10,000 BC (2008)",0.026795,0.212890,0.125045,0.263968,1.000000,0.253077,0.140955,0.085853,-0.010624,0.103974,...,0.272986,0.100676,0.108305,0.203082,0.261792,0.259721,0.114159,0.104310,0.216446,0.100899
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoolander (2001),0.077312,0.287615,0.216106,0.320612,0.259721,0.225272,0.310070,0.171385,0.045706,0.119440,...,0.326625,0.263349,0.022763,0.276482,0.337553,1.000000,0.145545,0.128239,0.358426,0.142170
Zootopia (2016),0.025886,0.244952,0.333470,0.089847,0.114159,0.091028,0.113085,0.097907,0.084366,0.244412,...,0.304788,0.174661,0.033600,0.242321,0.327761,0.145545,1.000000,0.072727,0.221144,0.048893
eXistenZ (1999),0.203163,0.082489,0.192469,0.151127,0.104310,0.078528,0.114561,0.034550,0.021150,0.146227,...,0.108026,0.046039,0.182945,0.170724,0.101105,0.128239,0.072727,1.000000,0.180807,0.159192
xXx (2002),0.078863,0.262600,0.111916,0.158846,0.216446,0.182338,0.270839,0.105648,0.054482,0.169530,...,0.286186,0.207324,0.096744,0.231546,0.228806,0.358426,0.221144,0.180807,1.000000,0.086811
¡Three Amigos! (1986),0.365934,0.154255,0.021727,0.143195,0.100899,0.110370,0.198986,0.136960,0.024007,0.024361,...,0.133337,0.082779,0.176441,0.215058,0.192190,0.142170,0.048893,0.159192,0.086811,1.000000

In [77]:
a = dfsimilaridade.loc[['Chinatown (1974)']]

In [51]:
a.sum().sort_values(ascending=False).head(20)

title
Chinatown (1974)                                                               1.000000
Vertigo (1958)                                                                 0.563670
Rear Window (1954)                                                             0.561562
On the Waterfront (1954)                                                       0.517846
Deer Hunter, The (1978)                                                        0.516370
Maltese Falcon, The (1941)                                                     0.515949
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)    0.514489
Taxi Driver (1976)                                                             0.507050
Citizen Kane (1941)                                                            0.504404
Third Man, The (1949)                                                          0.499686
Psycho (1960)                                                                  0.497968
L.A. Confidential (1997)                                                       0.496055
Graduate, The (1967)                                                           0.490150
Apocalypse Now (1979)                                                          0.488981
North by Northwest (1959)                                                      0.475072
Killing Fields, The (1984)                                                     0.460850
Midnight Cowboy (1969)                                                         0.456951
Casablanca (1942)                                                              0.456900
Godfather: Part II, The (1974)                                                 0.454439
2001: A Space Odyssey (1968)                                                   0.453356
dtype: float64

In [80]:
#---FUNÇÃO QUE UTILIZA COMO PARÂMETROS, O NOME DO FILME E A NOTA DO USUÁRIO---#
def nota_similaridade(nome_do_filme, nota_do_usuario):
    nota = dfsimilaridade[nome_do_filme]*(nota_do_usuario-2.5)
    #---BUSCAMOS DENTRO DO NOSSO DATAFRAME DE SIMILARIDADE, O NOME DO FILME E MULTIPLICAMOS PELA NOTA DO USUÁRIO - 2.5---#
    #---2.5 É A METADE DA NOTA MÁXIMA, 5, A SUBTRAÇÃO POR 2.5 DEIXA OS VALORES MAIS COMPREENSÍVEIS NA HORA DE DEFINIR---#
    #---SE AQUELE FILME É BOM OU NÃO PARA O USUÁRIO---#
    nota = nota.sort_values(ascending=False)
    #---ANTES DE FINALIZAR A FUNÇÃO, RETORNAMOS OS VALORES DA VARIÁVEL NOTA EM ORDEM DECRESCENTE---#
    
    return nota
    #---RETORNAMOS A VARIÁVEL NOTA COMO RESULTADO DA FUNÇÃO---#

In [82]:
#---NA LISTA MEUUSUARIO, COLOCAMOS OS FILMES, SEU ANO DE LANÇAMENTO ENTRE PARENTESES E APÓS ISSO, A NOTA---#
meuusuario = [("Shutter Island (2010)", 4),("Twilight (2008)", 5), ("Lemony Snicket's A Series of Unfortunate Events (2004)", 5)] 
              #("Chinatown (1974)", 5)]

filmes_similares = pd.DataFrame()
#---CRIAMOS OUTRO DF, PARA GUARDAR OS TÍTULOS DOS FILMES E O ÍNDICE DE SIMILARIDADE---#
for filme, nota_user in meuusuario:
    #---NO FOR LOOP, USAMOS DOIS ITENS, FILMES E A NOTA DO USUÁRIO DENTRO DA NOSSA LISTA MEUUSUARIO---#
    filmes_similares = filmes_similares.append(nota_similaridade(filme, nota_user), ignore_index=True)
    #---UTILIZAMOS A FUNÇÃO NOTA_SIMILARIDADE E ADICIONAMOS OS RESULTADOS NO NOSSO DF---#
filmes_similares.sum().sort_values(ascending=False)
#---FAZEMOS A SOMA DOS VALORES DE SIMILARIDADE E VISUALIZAMOS OS 50 COM MAIOR PROBABILIDADE DO USUARIO GOSTAR---#

Twilight (2008)                                               3.507564
Lemony Snicket's A Series of Unfortunate Events (2004)        3.467684
Shutter Island (2010)                                         2.530899
Scott Pilgrim vs. the World (2010)                            2.459615
The Hunger Games (2012)                                       2.411856
                                                                ...
Exit to Eden (1994)                                          -0.090918
Drop Zone (1994)                                             -0.093313
Sex, Lies, and Videotape (1989)                              -0.096055
Like Water for Chocolate (Como agua para chocolate) (1992)   -0.117536
Piano, The (1993)                                            -0.138098
Length: 2269, dtype: float64